# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vasp',
            old_name='Password',
            new_name='password',
        ),
    ]
