# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0002_auto_20180403_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vasp',
            name='email_id',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
