# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('mustafa town', 'mustafa town'), ('iqbal town', 'iqbal town'), ('johar town', 'johar town'), ('defence', 'defence')], default='mustafa town', max_length=30)),
                ('rate_locality', models.CharField(max_length=20)),
                ('rate_cleanliness', models.CharField(max_length=20)),
                ('rate_security', models.CharField(max_length=20)),
                ('rate_parks', models.CharField(max_length=20)),
                ('playGrounds', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('mustafa town', 'mustafa town'), ('johar town', 'johar town'), ('iqbal town', 'iqbal town'), ('defence', 'defence')], default='mustafa_town', max_length=30)),
                ('propertyTitle', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=20000)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], default='sale', max_length=30)),
                ('price', models.CharField(max_length=100)),
                ('Rooms', models.CharField(max_length=100)),
                ('BathRooms', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=100)),
                ('buildingAge', models.CharField(max_length=100)),
                ('freeParking', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=30)),
                ('swimmingPool', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=30)),
                ('airCondition', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=30)),
                ('sqft_Measurement', models.CharField(max_length=100)),
                ('contactName', models.CharField(max_length=100)),
                ('contactEmail', models.CharField(max_length=100)),
                ('contactPhone', models.CharField(max_length=100)),
                ('user', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mymodels', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('type', models.CharField(choices=[('interior designer', 'interior designer'), ('architect Engineers', 'architect Engineers'), ('Valuation services', 'Valuation services')], default='Valuation services', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
