# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0002_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='address',
        ),
        migrations.AlterField(
            model_name='products',
            name='BathRooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='Rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='postalCode',
            field=models.IntegerField(),
        ),
    ]
