# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0003_auto_20180512_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
