# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0004_products_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localities',
            name='location',
            field=models.IntegerField(choices=[('mustafa town', 'mustafa town'), ('iqbal town', 'iqbal town'), ('johar town', 'johar town'), ('defence', 'defence')], default='johar town'),
        ),
        migrations.AlterField(
            model_name='localities',
            name='playGrounds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localities',
            name='rate_cleanliness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localities',
            name='rate_locality',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localities',
            name='rate_parks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localities',
            name='rate_security',
            field=models.IntegerField(),
        ),
    ]
