# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0005_auto_20180513_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localities',
            name='location',
            field=models.CharField(choices=[('mustafa town', 'mustafa town'), ('iqbal town', 'iqbal town'), ('johar town', 'johar town'), ('defence', 'defence')], default='johar town', max_length=136),
        ),
    ]
