# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0007_localities_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localities',
            name='location',
            field=models.CharField(choices=[('mustafa town', 'mustafa town'), ('iqbal town', 'iqbal town'), ('johar town', 'johar town'), ('defence', 'defence'), ('defence', 'defence'), ('Awan town', 'Awan town'), ('Eden', 'Eden'), ('Wapda town', 'Wapda town')], default='johar town', max_length=136),
        ),
    ]
