# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0008_auto_20180625_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='localities',
            name='description',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
    ]
